# tmux configuration

# Leader key
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Enable mouse scroll
set -g mouse on

# Custom bindings

## Pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## Resize panes
bind < resize-pane -L 10
bind > resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10

## Window selection
bind H select-window -p
bind L select-window -n

