# tmux configuration

# use vim bindings for window selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload tmux config
bind r source-file ~/.tmux.conf

